routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| The order of routes must be like this, specially the 'goto' shoud be after 'shorturls'
|
*/

Auth::routes();

/** home route  */
Route::get('/', 'HomeController@index')->middleware('auth')->name('home');

/** shorturls routes  */
Route::resource('shorturls', 'ShorturlController');
Route::get('getdata', 'ShorturlController@getData')->name('shorturls.getdata');
Route::get('getlogdata', 'ShorturlController@getLogData')->name('shorturls.getlogdata');

/** redirect to original url  */
Route::get('/{key}', 'HomeController@goto')->name('goto');

/** switch languages route  */
Route::get('lang/{lang}', 'LanguageController@switchLang')->name('lang.switch');

app/Models/Shorturl.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Log;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;

class Shorturl extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'original_url',
        'key',
        'create_by',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function create_by()
    {
        return $this->belongsTo(User::class, 'create_by', 'id');
    }

    public function logs()
    {
        return $this->hasMany(Log::class);
    }

    public function for_current_user()
    {
        return ($this->create_by == Auth::user()->id) ;
    }

}

app/Http/Controllers/ShorturlController.php
<?php

namespace App\Http\Controllers;

use App\Models\Shorturl;
use App\Models\Log;

use Yajra\DataTables\Facades\DataTables;
use App\Http\Requests\StoreUrlRequest;
use Illuminate\Support\Facades\Auth;
use App\Http\Traits\ShorturlTrait;
use Illuminate\Http\Request;


class ShorturlController extends Controller
{
    use ShorturlTrait; 

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('shorturls.home');
    }


    public function getData()
    {
        $query = Shorturl::query()->where('create_by', Auth::user()->id)->orderBy('created_at', 'desc');
        $columns = DataTables::of($query);
        $columns
            ->editColumn('original_url', function (Shorturl $row) {
                return '<a href="'.($row->original_url ?? '#') .'" >'.  ($row->original_url ?? '#') . '</a>' ;

            })
            ->editColumn('key', function (Shorturl $row) {
                return '<a href="'. route('goto',$row->key ?? '') .'" >'.  short_url_full_form($row->key ?? '') . '</a>' ;
            })
            ->addColumn('actions', function (Shorturl $row) {
                $actions = '';
                    if(Auth::check() && $row->for_current_user()){
                        $actions .= '<a class="btn btn-xs btn-primary" href="' . route('shorturls.show', $row->id) . '" title="' . trans('global.view') . '">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </a> ';

                        $actions .= '<form action="' . route('shorturls.destroy', $row->id) . '" method="POST" onsubmit="ConfirmDelete()" style="display: inline-block;">
                            <input name="_method" value="DELETE" type="hidden">
                            ' . csrf_field() . '
                            <button type="submit" class="btn btn-xs btn-danger" title="' . trans('global.delete') . '"><i class="fa fa-trash" aria-hidden="true"></i></button>
                        </form>';
                    }
                return $actions;
            })
            ->rawColumns(['original_url', 'key', 'actions'])
            ->escapeColumns(['actions']);
        return $columns->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shorturls.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\StoreUrlRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUrlRequest $request)
    {
        if (Shorturl::count() >=20) {
            Shorturl::orderBy('created_at', 'asc')->limit(1)->delete();
        }
        $key = $this->getUniqueKey();
        $request->request->add(['key' => $key]); 
        $request->request->add(['create_by' => Auth::user()->id]); 
        $shorturl = Shorturl::create($request->all());
        if($shorturl)
            return redirect()->route('shorturls.index')->withToastSuccess(trans('global.url_create_success'));
        return redirect()->route('shorturls.index')->withToastError(trans('global.url_create_error'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Shorturl $shorturl
     * @return \Illuminate\Http\Response
     */
    public function show(Shorturl $shorturl)
    {
        return view('shorturls.show', compact('shorturl'));
    }

    public function getLogData(Request $request)
    {
    
        $query = Log::query()->where('shorturl_id', $request->get('shorturl_id') )->orderBy('access_time', 'desc');
        $columns = DataTables::of($query);
        $columns
            ->editColumn('user_id', function (Log $row) {
                return ($row->user->name ?? '') ;
            })
            ->editColumn('id_adress', function (Log $row) {
                return ($row->id_adress ?? '') ;
            })
            ->editColumn('country', function (Log $row) {
                return ($row->country ?? '') ;
            })
            ->editColumn('user_agent_navigator', function (Log $row) {
                return ($row->user_agent_navigator ?? '') ;
            })
            ->editColumn('access_time', function (Log $row) {
                return ($row->access_time ?? '') ;
            })
            ->rawColumns(['user_id', 'access_time', 'id_adress', 'country', 'user_agent_navigator'])
            ->escapeColumns(['actions']);
        return $columns->make(true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Shorturl $shorturl
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shorturl $shorturl)
    {
        abort_unless($shorturl->for_current_user(), 403);
        $shorturl->delete();
        if($shorturl)
            return back()->withToastSuccess(trans('global.url_create_success'));
        return back()->withToastError(trans('global.url_delete_error'));

    }

}

resources/views/shorturls/create.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row" >
                        <div class="col-md-10" >
                            {{ trans('global.shorturllist') }}
                        </div>
                    </div>

                
                </div>
                <div class="card-body">
                    <form action="{{ route("shorturls.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="original_url">{{ trans('global.originalurl') }} <span class="text-danger">*</span></label>
                            <div class="col-sm-10">
                                <input type="text" id="original_url" name="original_url" class="form-control {{ $errors->has('original_url') ? 'border-danger' : '' }}"
                                 value="{{ old('original_url', isset($shorturl) ? $shorturl->original_url : '') }}">
                                @if($errors->has('original_url'))
                                    <span class="form-text m-b-none text-danger">
                                        {{ $errors->first('original_url') }}
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-secondary btn-sm" href="{{ route("shorturls.index") }}">{{ trans('global.cancel') }}</a>
                                <button class="btn btn-primary btn-sm" type="submit">{{ trans('global.save') }}</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('scripts')
@endsection

resources/views/shorturls/home.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{ asset('css/datatables.min.css') }}" rel="stylesheet">
    <style>
        div.html5buttons {
            float: right !important;
        }
        div#DataTables_Table_0_wrapper{
            overflow-x: auto;
        }
    </style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row" >
                        <div class="col-md-8" >
                            {{ trans('global.shorturllist') }}
                        </div>
                        @auth
                            @can('add_shorturl')
                                
                                <div class="col-md-4" >
                                    <a class="btn btn-success btn-sm float-right" href="{{ route("shorturls.create") }}">
                                        {{ trans('global.add') }} {{ trans('global.shorturl') }}
                                    </a>
                                </div>
                            @else
                                <div class="col-md-4 p-2 bg-danger text-white rounded" >
                                    {{ trans('global.max_lin_user') }}
                                </div>
                            @endcan
                        @endauth
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped shorturltable" >
                        <thead>
                          <tr>
                            <th scope="col">{{ trans('global.originalurl') }}</th>
                            <th scope="col">{{ trans('global.shorturl') }}</th>
                            <th scope="col">{{ trans('global.actions') }}</th>
                          </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        <footer>
                            <tr>
                              <th scope="col">{{ trans('global.originalurl') }}</th>
                              <th scope="col">{{ trans('global.shorturl') }}</th>
                              <th scope="col">{{ trans('global.actions') }}</th>
                            </tr>
                          </footer>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}" ></script>

        <!-- Page-Level Scripts -->
        <script>
            $(document).ready(function(){
  
                $('.shorturltable').DataTable({
                    processing: true,
                    serverSide: true,
                    responsive: true,
                    dom: '<"html5buttons"B>lTfgitp',
                    buttons: [
                        
                        {extend: 'excel', title: '{{ trans("global.shorturllist") }}'},
                        {extend: 'pdf', title: '{{ trans("global.shorturllist") }}'},
                        {
                            extend: 'print',
                            customize: function (win){
                                $(win.document.body).addClass('white-bg');
                                $(win.document.body).css('font-size', '10px');
                                $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                            }
                        }
                    ],
                    ajax: '{{ route("shorturls.getdata") }}',
                    order: [[ 0, 'asc' ]],
                    columns: [
                        { data: 'original_url', name: 'original_url', searchable: true, orderable: true },
                        { data: 'key', name: 'key', searchable: true, orderable: true },
                        { data: 'actions', name: 'actions', searchable: true, orderable: true },
                    ]

                });
            });
            function ConfirmDelete()
            {
                var x = confirm(@json(trans('global.areYouSure')));
                if (x)
                    return true;
                else
                    return false;
            }
        </script>

@endsection

resources/views/shorturls/show.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{ asset('css/datatables.min.css') }}" rel="stylesheet">
    <style>
        div.html5buttons {
            float: right !important;
        }
        div#DataTables_Table_0_wrapper{
            overflow-x: auto;
        }
    </style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row" >
                        <div class="col-md-8" >
                            {{ trans('global.logs') }} {{ trans('global.of') }} <a href="{{ route('goto', $shorturl->key )}}" target="_blank"> {{ $shorturl->key }} </a>
                        </div>

                        <div class="col-md-4" >
                            <a class="btn btn-secondary btn-sm float-right" href="{{ route("shorturls.index") }}">{{ trans('global.back') }}</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped logs" >
                        <thead>
                          <tr>
                            <th scope="col">{{ trans('global.user') }}</th>
                            <th scope="col">{{ trans('global.ip_adress') }}</th>
                            <th scope="col">{{ trans('global.country') }}</th>
                            <th scope="col">{{ trans('global.user_agent_navigator') }}</th>
                            <th scope="col">{{ trans('global.access_time') }}</th>
                          </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        <footer>
                            <tr>
                              <th scope="col">{{ trans('global.user') }}</th>
                              <th scope="col">{{ trans('global.ip_adress') }}</th>
                              <th scope="col">{{ trans('global.country') }}</th>
                              <th scope="col">{{ trans('global.user_agent_navigator') }}</th>
                              <th scope="col">{{ trans('global.access_time') }}</th>
                            </tr>
                          </footer>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}" ></script>

        <!-- Page-Level Scripts -->
        <script>
            $(document).ready(function(){
  
                $('.logs').DataTable({
                    processing: true,
                    serverSide: true,
                    responsive: true,
                    dom: '<"html5buttons"B>lTfgitp',
                    buttons: [
                        
                        {extend: 'excel', title: '{{ trans("global.shorturllist") }}'},
                        {extend: 'pdf', title: '{{ trans("global.shorturllist") }}'},
                        {
                            extend: 'print',
                            customize: function (win){
                                $(win.document.body).addClass('white-bg');
                                $(win.document.body).css('font-size', '10px');
                                $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                            }
                        }
                    ],
                    ajax: {
                        url: '{{ route("shorturls.getlogdata") }}',
                        data: function (d) {
                            d.shorturl_id = '{{$shorturl->id}}'
                        }
                    },
                    order: [[ 0, 'asc' ]],
                    columns: [
                        { data: 'user_id', name: 'user_id', searchable: true, orderable: true },
                        { data: 'id_adress', name: 'id_adress', searchable: true, orderable: true },
                        { data: 'country', name: 'country', searchable: true, orderable: true },
                        { data: 'user_agent_navigator', name: 'user_agent_navigator', searchable: true, orderable: true },
                        { data: 'access_time', name: 'access_time', searchable: true, orderable: true },
                    ]
                });
            });
        </script>

@endsection